### ISSUE TITLE
Dijsktra algo

### ISSUE THREAD

**Issue by Knackie** [Knackie/algorithmshacktoberfest2021#17]
- Make the dijsktra algorithm in différents language 
- Update readme when it's done

**Comment by leli-1** [comment]
can you assign this to me for python ?

**Comment by virajmavani** [comment]
I can implement it in Java. Can you assign it to me?

**Comment by yadavgaurav251** [comment]
I would like to do it in c++ ,can you assign it to me?

**Comment by yadavgaurav251** [comment]
Hey @Knackie ,  I have sent a pull request #46  for this issue. Kindly review it and please add the hacktoberfest-accepted label to this pull request and previous accepted pull request.

**Comment by Knackie** [comment]
label already add. i go accept PR

**Comment by tzAcee** [comment]
Can I do it in c# :b?
