### ISSUE TITLE
complete algorithms

### ISSUE THREAD

**Issue by Knackie** [Knackie/algorithmshacktoberfest2021#2]
Complete the list of differents algorithms in language

**Comment by mccarthykp** [comment]
Hi! Can I add some algos in the JS list?

**Comment by ghanender-chauhan** [comment]
hi can you assign me this ..I will do in python

**Comment by virajmavani** [comment]
I can add LCS in Python and Java. Should they be two PRs or in a single one?

**Comment by Knackie** [comment]
> I can add LCS in Python and Java. Should they be two PRs or in a single one?
if you can make 2 PR, thanks
